### ISSUE TITLE
Crashes under AlienDalvik with µg UnifiedNlp - zoomLevel

### ISSUE THREAD

**Issue by vermut** [mvglasow/satstat#58]
[Third screen](https://github.com/microg/android_packages_apps_UnifiedNlp/issues/74#issuecomment-196517023) died with
```
E/AndroidRuntime(14308): java.lang.IllegalArgumentException: zoomLevel must not be negative: -1
E/AndroidRuntime(14308):    at org.mapsforge.map.model.MapViewPosition.setZoomLevel(MapViewPosition.java:394)
E/AndroidRuntime(14308):    at com.vonglasow.michael.satstat.MainActivity.updateMap(MainActivity.java:1999)
E/AndroidRuntime(14308):    at com.vonglasow.michael.satstat.MainActivity.onLocationChanged(MainActivity.java:1217)
E/AndroidRuntime(14308):    at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:263)
E/AndroidRuntime(14308):    at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:196)
E/AndroidRuntime(14308):    at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:212)
E/AndroidRuntime(14308):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(14308):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(14308):    at android.app.ActivityThread.main(ActivityThread.java:4781)
E/AndroidRuntime(14308):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(14308):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(14308):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:805)
E/AndroidRuntime(14308):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:568)
E/AndroidRuntime(14308):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager( 5917):   Force finishing activity com.vonglasow.michael.satstat/.MainActivity
W/ActivityManager( 5917): Activity pause timeout for ActivityRecord{41d8d058 surfaceId:14 com.vonglasow.michael.satstat/.MainActivity}
I/ActivityManager( 5917): ACTIVITY DESTROYING: r = ActivityRecord{41d8d058 surfaceId:14 com.vonglasow.michael.satstat/.MainActivity}, index = 3
D/ActivityManager( 5917): notifySurfaceDiedIfNeeded( 3) : ActivityRecord{41d8d058 surfaceId:14 com.vonglasow.michael.satstat/.MainActivity}
```

**Comment by mvglasow** [comment]
Thanks for the detailed log output – that turned out to be an easy one to fix!

**Comment by rfvermut** [comment]
Would there be an intermediate release?

**Comment by mvglasow** [comment]
I'm planning to release a new version, currently I'm going through the other tickets to see what else I'll add to it.
